In [1]:
import pandas as pd

import acquire
import prepare
import model_target_sex as m

pd.set_option('display.float_format', '{:.2f}'.format)

In [2]:
train, validate, test = prepare.split_data(acquire.make_dataset())
X_train, y_train, X_val, y_val = m.prepare_train_validate(train, validate, m.MODEL_STRATEGY_DICTIONARY['measurement_ratio'])
X_test, y_test = m.prepare_test(train, test, m.MODEL_STRATEGY_DICTIONARY['measurement_ratio'])
output, y_pred, y_prob = m.make_radius_neighbor_model_test(X_train, y_train, X_val, y_val, X_test, y_test, 0.50)

In [3]:
y_pred

     case     sex predicted  probability_male  probability_female
94     95    male    female              0.50                0.50
25     26    male      male              1.00                0.00
78     79    male      male              1.00                0.00
10     11  female    female              0.00                1.00
102   103    male      male              1.00                0.00
29     30  female    female              0.00                1.00
98     99  female    female              0.00                1.00
0       1    male      male              1.00                0.00
56     57  female    female              0.00                1.00
84     85    male      male              1.00                0.00
95     96    male      male              1.00                0.00
49     50  female    female              0.00                1.00
92     93    male      male              1.00                0.00
7       8  female    female              0.00                1.00
81     82  female    female              0.00                1.00
101   102  female    female              0.00                1.00
1       2  female    female              0.25                0.75
93     94    male      male              1.00                0.00
86     87    male      male              1.00                0.00
5       6  female    female              0.00                1.00
47     48    male      male              1.00                0.00
97     98    male      male              1.00                0.00
31     32  female    female              0.00                1.00
75     76    male      male              1.00                0.00
27     28    male      male              1.00                0.00
42     43  female    female              0.00                1.00
46     47    male      male              1.00                0.00
91     92    male      male              1.00                0.00
51     52    male      male              1.00                0.00
100   101    male      male              1.00                0.00
48     49    male      male              1.00                0.00
73     74  female    female              0.00                1.00
37     38    male      male              1.00                0.00
69     70  female    female              0.00                1.00
99    100    male      male              1.00                0.00

In [4]:
train, validate, test = prepare.split_data(acquire.make_dataset())
model_df = m.model_maker(train, validate, 0.58)

In [5]:
model_df

,model,train_accuracy,validate_accuracy,accuracy_change,better_than_baseline,modeling_strategy
0,Logistic Regression,0.77,0.69,0.09,True,measurement_only
1,Support Vector Classification,0.81,0.77,0.04,True,measurement_only
2,K-Nearest Neighbors Classification,0.74,0.69,0.06,True,measurement_only
3,Radius Neighbors Classification,0.73,0.69,0.04,True,measurement_only
4,Nearest Centroid Classification,0.67,0.60,0.07,True,measurement_only
5,Logistic Regression,0.76,0.69,0.07,True,ratio_only
6,Support Vector Classification,0.81,0.77,0.04,True,ratio_only
7,K-Nearest Neighbors Classification,0.81,0.74,0.07,True,ratio_only
8,Radius Neighbors Classification,0.81,0.77,0.04,True,ratio_only
9,Nearest Centroid Classification,0.71,0.63,0.09,True,ratio_only
10,Logistic Regression,0.79,0.71,0.07,True,measurement_ratio
11,Support Vector Classification,0.84,0.77,0.07,True,measurement_ratio
12,K-Nearest Neighbors Classification,0.77,0.69,0.09,True,measurement_ratio
13,Radius Neighbors Classification,0.96,0.94,0.01,True,measurement_ratio
14,Nearest Centroid Classification,0.70,0.63,0.07,True,measurement_ratio

In [6]:
X_train, y_train, X_val, y_val = m.prepare_train_validate(train, validate, m.MODEL_STRATEGY_DICTIONARY['measurement_ratio'])
met_t, met_val = m.make_radius_neighbor_model(X_train, y_train, X_val, y_val, 0.5, return_report = True)
met_val

{'female': {'precision': 0.8823529411764706,
  'recall': 1.0,
  'f1-score': 0.9375,
  'support': 15},
 'male': {'precision': 1.0,
  'recall': 0.9,
  'f1-score': 0.9473684210526316,
  'support': 20},
 'accuracy': 0.9428571428571428,
 'macro avg': {'precision': 0.9411764705882353,
  'recall': 0.95,
  'f1-score': 0.9424342105263158,
  'support': 35},
 'weighted avg': {'precision': 0.9495798319327731,
  'recall': 0.9428571428571428,
  'f1-score': 0.9431390977443609,
  'support': 35}}

In [7]:
train, validate, test = prepare.split_data(acquire.make_dataset())
prepare.make_sex_distribution_df(train, validate, test)

    dataset  proportion_male  proportion_female  total_male  total_female
0     train             0.59               0.41          41            29
1  validate             0.57               0.43          20            15
2      test             0.60               0.40          21            14

In [8]:
train = model_target_sex.make_modeling_columns(train)
train.sample(2)

NameError: name 'model_target_sex' is not defined

In [ ]:
train = model_target_sex.drop_columns(train)
train.sample(2)

In [ ]:
# X, y = model_target_sex.make_X_and_y(train)
# X.sample(2)

In [ ]:
train, validate, test = prepare.split_data(acquire.make_dataset())
X_train, y_train, X_val, y_val = model_target_sex.prepare_train_validate(train, validate)